name: setup

on:
 schedule:
  - cron: '0 */8 * * *'
 workflow_dispatch:

jobs:
 update-repo:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repostory
     uses: actions/checkout@v3

   - name: Update README timestamp
     run: |
      export TZ="Asia/Jakarta"
      TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")
      echo "Latest updated: $TIMESTAMP" > README.md

   - name: Configure git
     run: |
      git config user.name "ahmdsalim"
      git config user.email "salimahmad14823@gmail.com"
      git config user.signingkey 43709EE9978C6C9B
      echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
      gpg --list-secret-keys

   - name: Commit changes
     run: |
      git add README.md
      git commit -S -m "Auto update README at $TIMESTAMP" || echo "No changes to commit"

   - name: Push changes
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |
      git push origin main
